### ISSUE TITLE
Could not remove an access from a file

### ISSUE THREAD

**Issue by mrvahedi68** [pondersource/oc-sciencemesh#11]
When we share a file with one of our contacts, then we have a button for removing access.
Clicking on this button will occur an error with this text: `No Provider with id "ocFederatedSharing" found`

**Comment by navid-dada** [comment]
it is the same  with issue #7

**Comment by mrvahedi68** [comment]
This error occurs on line 33  of `Share20OcsController.php`.

I think this is a problem with `registerProvider` that not configured this provider.
