### ISSUE TITLE
einstein cannot see the shared files that he shred with marie.

### ISSUE THREAD

**Issue by navid-dada** [pondersource/oc-sciencemesh#17]
When Einstein shares a file with Marie. it is shared with marine and marine can see it in pending (waiting for acceptance) but the shared file is not listed in shared with others menu.

**Comment by mrvahedi68** [comment]
I checked it and there is no problem. Shred files appear inside the `shared with others` section.

**Comment by mrvahedi68** [comment]
I think @navid-dada we can have a knowledge sharing about this problem, maybe we use different vesions.

**Comment by michielbdejong** [comment]
This was fixed
