### ISSUE TITLE
Marie can't see received shares inside `shared with you`

### ISSUE THREAD

**Issue by mrvahedi68** [pondersource/oc-sciencemesh#18]
When Marie receives a share she can see it inside the `Shared with you` section with `pending` status, But when she accepts a share she can not see that share anymore.

**Comment by navid-dada** [comment]
https://reva.link/docs/tutorials/share-tutorial/
it can provide some work around about local testing

**Comment by mrvahedi68** [comment]
Yes, this link shows how we can start two reva instances in same machine. I'll try that.

**Comment by michielbdejong** [comment]
This was fixed
