### ISSUE TITLE
Missing "elem" id selector in contacts template

### ISSUE THREAD

**Issue by mirekys** [pondersource/oc-sciencemesh#20]
JS code for contacts tab fails to register [onClick](https://github.com/pondersource/oc-sciencemesh/blob/main/js/contacts.js#L39) handler, because there is no element with `id="elem"`
in the [contacts](https://github.com/pondersource/oc-sciencemesh/blob/main/templates/contacts.php) template

This results in failure to accept any incoming sciencemesh contacts (that ajax call to `/contacts/accept` inside onClick wouldn't be called):

<img width="502" alt="Screenshot 2022-08-03 at 14 19 49" src="https://user-images.githubusercontent.com/646743/182606024-294011bb-8324-42f7-9c18-5925ebe7159d.png">

**Comment by navid-dada** [comment]
the whole content should be enclosed in : 
`document.addEventListener("DOMContentLoaded", function(event) {})`

**Comment by navid-dada** [comment]
@ishifoev can you review this commit?

**Comment by navid-dada** [comment]
this issue is moved to #21
