### ISSUE TITLE
"Generate" button missing in GUI?

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/oc-sciencemesh#29]
This is what I see now in the latest build:
<img width="941" alt="Screenshot 2022-12-21 at 09 37 20" src="https://user-images.githubusercontent.com/408412/208858591-c252588e-2c21-4ef0-9366-3259945850b6.png">

@parhamin2010 where should I click? Is there some UI element missing from the page?

**Comment by parhamin2010** [comment]
I pushed the fix here
https://github.com/pondersource/oc-sciencemesh/issues/30

**Comment by michielbdejong** [comment]
Leaving this issue open until https://github.com/pondersource/oc-sciencemesh/pull/31 is merged.

**Comment by michielbdejong** [comment]
#31 is merged now
