### ISSUE TITLE
Sciencemesh client app GUI improvments.

### ISSUE THREAD

**Issue by parhamin2010** [pondersource/oc-sciencemesh#30]
I checked the current version on the `frontend` branch and I think there should be some Improvements that make the app more user-friendly: 
1- Modify the `generate` page  to help the user to find out that the  **`Generate a new token`** is  clickable. 
2- Make a decision about the `Verify token`. Do you think it's necessary? we can replace it with a `COPY` button to put the token value inside the clipboard. 
![1-2](https://user-images.githubusercontent.com/10582747/210257279-beae74d5-a36f-4ae5-bdc2-0cec5bc6e6b3.jpg)

3- `Check token` should be changed to `Accept Token` on accept page.
4- An error will appear if the token is invalid. I think this message should have a red design if token validation failed or it should have a green design if token validation/acceptance flow was successful. 
![3-4](https://user-images.githubusercontent.com/10582747/210257295-25fa60e4-8794-4af0-b395-ed93ce204a73.jpg)

5- the phrase `No connection with Reva` should be changed to `No Sciencemesh Connection` and it should be more emphasized in design.
![5](https://user-images.githubusercontent.com/10582747/210257305-87efcde5-b789-4b06-9a82-f8743a38827f.jpg)

**Comment by michielbdejong** [comment]
Leaving this issue open until https://github.com/pondersource/oc-sciencemesh/pull/31 is merged.

**Comment by navid-dada** [comment]
@michielbdejong can you declear us about #2?

**Comment by michielbdejong** [comment]
Change "Verify Token" to "View Token"

**Comment by michielbdejong** [comment]
@parhamin2010 created a 'Copy' button but it's not working yet with jQuery, so it's commented out

**Comment by michielbdejong** [comment]
> Maybe change "token" to "invite"?

We couldn't reach consensus on a better name yet, let's keep it as "token" until we do

**Comment by parhamin2010** [comment]
see this issue for more information
https://github.com/pondersource/nc-sciencemesh/pull/228

**Comment by parhamin2010** [comment]
![1](https://user-images.githubusercontent.com/25672014/211509316-4f421e4c-3db8-49ff-a837-1e839c26ec6d.png)
![2](https://user-images.githubusercontent.com/25672014/211509348-ad0552d6-d0e9-4ce4-bdae-465a64d2dc80.png)
![3](https://user-images.githubusercontent.com/25672014/211509356-97508911-eb39-488b-8e15-01fb2bc47866.png)

Here're the fixes
