### ISSUE TITLE
Contacts not rendered properly

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/oc-sciencemesh#36]
Even after #35 we're left with a broken view for contacts, this needs fixing:

<img width="1495" alt="Screenshot 2023-01-11 at 13 03 26" src="https://user-images.githubusercontent.com/408412/211801800-aaa8ab44-a812-441d-99f4-7caa0c043fac.png">

**Comment by parhamin2010** [comment]
It was missing css again. I added them here:
https://github.com/pondersource/oc-sciencemesh/pull/37#issue-1529438940

**Comment by michielbdejong** [comment]
I'm still seeing this somehow, when working with the main branch of this repo.
![Screenshot 2023-01-24 at 15 13 16](https://user-images.githubusercontent.com/408412/214317884-d87a526d-da27-46cb-899e-62e6c5e4e569.png)

**Comment by parhamin2010** [comment]
Created a PR for this fix here
https://github.com/pondersource/oc-sciencemesh/pull/41

**Comment by michielbdejong** [comment]
I'm now seeing this:

![Screenshot 2023-01-24 at 17 02 41](https://user-images.githubusercontent.com/408412/214344450-4545114a-2ce5-4c67-90f4-40eb4445b68d.png)

Which is still not good.

**Comment by parhamin2010** [comment]
@michielbdejong try to check the cache again here.

**Comment by michielbdejong** [comment]
On NC it looks fine but on OC the icon was not cropped properly. Confirmed fixed now!

![Screenshot 2023-01-25 at 15 36 22](https://user-images.githubusercontent.com/408412/214592950-437d4a39-9c43-4c91-98ac-c19c30f6934c.png)
