### ISSUE TITLE
Marie not showing up in search results

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/oc-sciencemesh#4]
I'm able to run through the whole invite exchange and see Marie as a ScienceMesh contact of Einstein's on oc1.docker

But then when I try to share something with Marie, I see 'Federated' search results for roughly any string that contains an '@', but no sign that the search box knows about Marie.

**Comment by michielbdejong** [comment]
Have to dig into the owncloud sharee search code to see if it's actually referring this to the share provider or just dealing with it heuristically.

**Comment by michielbdejong** [comment]
Something like https://github.com/sciencemesh/nc-sciencemesh/blob/main/lib/Plugins/ScienceMeshSearchPlugin.php

**Comment by michielbdejong** [comment]
code passes through here: https://github.com/owncloud/core/blob/1fa4dc0/apps/files_sharing/lib/Controller/ShareesController.php#L586

**Comment by michielbdejong** [comment]
Let's add an if-statement to https://github.com/owncloud/core/blob/1fa4dc0/apps/files_sharing/lib/Controller/ShareesController.php#L166 and make that a PR to owncloud core

**Comment by navid-dada** [comment]
this problem is resolved on this repo: 
https://github.com/pondersource/core

**Comment by navid-dada** [comment]
Marie in sharee list is marked as SHARE_TYPE_REMOTE but in nextCloud it is characterized by SHARE_TYPE_SCIENCEMESH, 
should it change?
