### ISSUE TITLE
Check connection on admin setting dialogue for IOP URL

### ISSUE THREAD

**Issue by parhamin2010** [pondersource/oc-sciencemesh#48]
Referred to this feature:
https://github.com/pondersource/sciencemesh-php/issues/90

**Comment by michielbdejong** [comment]
I'm seeing this error in the web console:
```
Uncaught SyntaxError: missing } after function body          settings.js:148
note: { opened at line 1, column 18

**Comment by michielbdejong** [comment]
Nothing happens when I click the "connection test" button

**Comment by michielbdejong** [comment]
![Screenshot 2023-02-13 at 10 43 53](https://user-images.githubusercontent.com/408412/218424182-bd07b57e-402a-4190-b843-d2aea5388b6f.png)

**Comment by parhamin2010** [comment]
Fixes are here:
https://github.com/pondersource/oc-sciencemesh/pull/55
