### ISSUE TITLE
Accept message must be on the center

### ISSUE THREAD

**Issue by parhamin2010** [pondersource/oc-sciencemesh#64]
Referred to this:
https://github.com/pondersource/sciencemesh-php/issues/170

**Comment by parhamin2010** [comment]
There's issue from Reva API response.
Here's the issue detail:

1- Once user is already added to NC1 and user trys to open old token URL it returns this error message from Reva.
grpc forward invite request failed

2- Once user is opening a token URL like this:
https://meshdir.docker/meshdir?token=&providerDomain=
Same error returns from Reva without any differences.
grpc forward invite request failed

I'm reporting this error here as new issue.
https://github.com/pondersource/sciencemesh-php/issues/174

**Comment by michielbdejong** [comment]
https://github.com/pondersource/nc-sciencemesh/issues/250 is the sister-issue for this on nc-sciencemesh

**Comment by michielbdejong** [comment]
> There's issue from Reva API response. [...]

But that is unrelated to this issue, right?

**Comment by parhamin2010** [comment]
Yes.
